feat: GlobalException 및 ApiResponse 작성
eureka-final/pov-backend pull request #33
Opened 2024-11-22 09:32 UTC by leeseunghee00

## PR 설명
- GlobalException 및 ApiResponse 작성

## 📸 스크린샷

## 고민과 해결과정

2024-11-22 10:32 UTC, good4y requested changes

2024-11-22 10:32 UTC, good4y commented on src/main/java/net/pointofviews/common/exception/GlobalExceptionHandler.java
> +		return ResponseEntity.badRequest().body(ex.getMessage());
여기서 위에 작성해 둔 failure 메서드를 사용해야 합니다.

2024-11-22 14:55 UTC, leeseunghee00 commented on src/main/java/net/pointofviews/common/exception/GlobalExceptionHandler.java
> +		return ResponseEntity.badRequest().body(ex.getMessage());
ApiResponse 반환으로 변경했습니다! 다만, businessException 는 상태가 여러가지가 될 수 있어서 ResponseEntity 로 반환하되, body 형식은 ApiResponse 로 수정했습니다.

2024-11-23 04:17 UTC, good4y approved these changes

2024-11-23 06:30 UTC, merged